name: Deploy Site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  set-deploy-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get deployment target
        run: |
          TARGET=$(cat DEPLOY_STRATEGY)
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: check if target is valid
        if: success() && !contains(['gh-pages', 'firebase'], env.TARGET)
        run: echo 'Invalid Deployment Target' && exit 1

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: env.TARGET == 'gh-pages'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy Jekyll Site
      uses: sujaykundu777/jekyll-deploy-action@1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: env.TARGET == 'firebase'

    steps:
    - uses: actions/checkout@v2

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: build jekyll
      run: |
        bundle install
        bundle exec jekyll build

    - name: deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
